#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  build-nrf52.sh — Build nRF52 Factory Erase firmware
#
#  Usage:
#    ./scripts/macos/build-nrf52.sh [OPTIONS] [ENVIRONMENT]
#
#  OPTIONS:
#    --clean     Remove .pio/build/<env> before building
#    --verbose   Pass -v to pio run for detailed compiler output
#
#  ENVIRONMENT:
#    s140_nrf52_611_softdevice   S140 v6.1.1 — RAK, LilyGo, Heltec Node T114
#    s140_nrf52_730_softdevice   S140 v7.3.0 — Seeed, ms24sf1, ME25LS01
#    all                         Build both environments (default)
#
#  Output artifacts are placed in release/:
#    *.elf       ELF debug binary
#    *.uf2       UF2 drag-and-drop firmware
#    *-ota.zip   nrfutil DFU package
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SCRIPTS_PYTHON="${PROJECT_ROOT}/scripts/python"

cd "${PROJECT_ROOT}"

# ── Colours ───────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  G='\033[0;32m'; R='\033[0;31m'; B='\033[0;34m'; C='\033[0;36m'
  Y='\033[1;33m'; BOLD='\033[1m'; NC='\033[0m'
else
  G=''; R=''; B=''; C=''; Y=''; BOLD=''; NC=''
fi
info()    { echo -e "${B}ℹ  ${NC}${*}"; }
success() { echo -e "${G}✔  ${*}${NC}"; }
error()   { echo -e "${R}✖  ${*}${NC}" >&2; }
step()    { echo -e "\n${C}${BOLD}▸ ${*}${NC}"; }

ALL_ENVS=(s140_nrf52_611_softdevice s140_nrf52_730_softdevice)

# ── Argument parsing ──────────────────────────────────────────────────────────
ENV_ARG="all"
CLEAN=0
VERBOSE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --clean)        CLEAN=1 ;;
    --verbose|-v)   VERBOSE=1 ;;
    -*)             error "Unknown option: $1"; exit 1 ;;
    *)              ENV_ARG="$1" ;;
  esac
  shift
done

if [[ "${ENV_ARG}" == "all" ]]; then
  ENVS=("${ALL_ENVS[@]}")
else
  ENVS=("${ENV_ARG}")
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
PYTHON=$(command -v python3 || command -v python || echo "")
[[ -z "${PYTHON}" ]] && { error "python3 not found"; exit 1; }
command -v pio &>/dev/null || { error "pio not found. Run: uv tool install platformio"; exit 1; }

# ── Version ───────────────────────────────────────────────────────────────────
# Use APP_VERSION from environment if already set (CI), otherwise read from file
if [[ -z "${APP_VERSION:-}" ]]; then
  APP_VERSION="$("${PYTHON}" "${SCRIPTS_PYTHON}/buildinfo.py" long)"
fi
export APP_VERSION

OUTDIR="${PROJECT_ROOT}/build"
mkdir -p "${OUTDIR}"

echo -e "\n${BOLD}${B}════════════════════════════════════════════${NC}"
echo -e "${BOLD}${B}  🔨  nRF52 Factory Erase — Build           ${NC}"
echo -e "${BOLD}${B}════════════════════════════════════════════${NC}"
info "Version  : ${BOLD}${APP_VERSION}${NC}"
info "Targets  : ${BOLD}${ENVS[*]}${NC}"
info "Output   : ${BOLD}${OUTDIR}${NC}"

declare -a PASSED=() FAILED=()

for ENV in "${ENVS[@]}"; do
  step "Building ${ENV}…"

  if [[ ${CLEAN} -eq 1 ]]; then
    local_clean=".pio/build/${ENV}"
    if [[ -d "${local_clean}" ]]; then
      rm -rf "${local_clean}"
      info "  Cleaned ${local_clean}"
    fi
  fi

  pio pkg update -e "${ENV}" --silent 2>/dev/null || true

  PIO_ARGS=(run --environment "${ENV}")
  [[ ${VERBOSE} -eq 1 ]] && PIO_ARGS+=(-v)

  if pio "${PIO_ARGS[@]}"; then
    BASE="nrf52_factory_erase-${ENV}-${APP_VERSION}"

    cp ".pio/build/${ENV}/firmware.elf" "${OUTDIR}/${BASE}.elf"
    cp ".pio/build/${ENV}/firmware.zip" "${OUTDIR}/${BASE}-ota.zip" 2>/dev/null || true

    # UF2 is already generated by platformio-custom.py post-action;
    # copy it, or regenerate if missing.
    if [[ -f ".pio/build/${ENV}/firmware.uf2" ]]; then
      cp ".pio/build/${ENV}/firmware.uf2" "${OUTDIR}/${BASE}.uf2"
    else
      "${PYTHON}" "${SCRIPTS_PYTHON}/uf2conv.py" \
        ".pio/build/${ENV}/firmware.hex" \
        -c -o "${OUTDIR}/${BASE}.uf2" -f 0xADA52840
    fi

    PASSED+=("${ENV}")
    success "${BASE}"
  else
    FAILED+=("${ENV}")
    error "Build failed for ${ENV}"
  fi
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo -e "\n${BOLD}── Summary ─────────────────────────────────────${NC}"
for e in "${PASSED[@]}"; do echo -e "  ${G}✔ PASS${NC}  ${e}"; done
for e in "${FAILED[@]}"; do echo -e "  ${R}✖ FAIL${NC}  ${e}"; done
echo ""
ls -lh "${OUTDIR}"/*.uf2 "${OUTDIR}"/*.elf "${OUTDIR}"/*.zip 2>/dev/null | awk '{print "  "$NF, $5}'

(( ${#FAILED[@]} > 0 )) && exit 1 || success "All ${#PASSED[@]} build(s) complete → ${C}${OUTDIR}/${NC}"
